config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'admin', to: 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products do
    get :who_bought, on: :member
  end

  ## API

  get 'api/products', to: 'product_api#index'
  get 'api/products/:id', to: 'product_api#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/api_client.rb
class ApiClient < ApplicationRecord
  validates :name, uniqueness: true

  def generate_token
    api_key = SecureRandom.hex
    update(key: Digest::SHA512.hexdigest(api_key))

    api_key
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id, price: product.price)
    end
    current_item
  end

  def total_price
    line_items.sum(&:total_price)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart

  def total_price
    price * quantity
  end
end

app/models/order.rb
require 'pago'

class Order < ApplicationRecord
  enum pay_type:  {
    "Check" => 0,
    "Credit Card" => 1,
    "Purchase Order" => 2,
  }
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  has_many :line_items, dependent: :destroy

  def line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil

    case pay_type
      when "Check"
        payment_method = :check
        payment_details[:routing] = pay_type_params[:routing_number]
        payment_details[:account] = pay_type_params[:account_number]
      when "Credit Card"
        payment_method = :credit_card
        month, year = pay_type_params[:expiration_date].split(//)
        payment_details[:cc_num] = pay_type_params[:credit_card_number]
        payment_details[:expiration_month] = month
        payment_details[:expiration_year] = year
      when "Purchase Order"
        payment_method = :po
        payment_details[:po_num] = pay_type_params[:po_number]
    end

    payment_result = Pago.make_payment(order_id: id, payment_method: payment_method, payment_details: payment_details)

    if payment_result.succeeded?
      OrderMailer.received(self ).deliver_later
    else
      raise payment_result.error
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: { case_sensitive: false }
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image'
  }

  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :check_line_item_presence

  private

  def check_line_item_presence
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  has_secure_password

  after_destroy :ensure_an_admin_remains

  class Error < StandardError; end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = 10 # Order.count
    @user = User.find(session[:user_id])
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_with_basic_auth

  private

  ## Find credentials by name, render error unless the credentials are valid

  def authenticate_with_basic_auth
    name, token = ActionController::HttpAuthentication::Basic.user_name_and_password(request)
    @api_client = ApiClient.find_by(name: name)

    render(json: { errors: [{ detail: "Access Denied" }] }, status: 401) unless valid_key(token)
  end

  ## Secure compare DB with token & name
  
  def valid_key(token)
    @api_client && ActiveSupport::SecurityUtils.secure_compare(@api_client&.key, Digest::SHA512.hexdigest(token))
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_if(condition, record)
    render record if condition
  end

  def checkout_page
    controller_name == 'orders' && action_name == 'new'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_api_helper.rb
module ProductApiHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<!--<h1>Welcome <%#= @user.name %>></h1>-->

<p>
  It's <%= Time.now %>.
  We have <%= pluralize(@total_orders, "order") %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--    <link-->
<!--      rel="stylesheet"-->
<!--      href="https://unpkg.com/@shopify/polaris@4.13.1/styles.min.css"-->
<!--      />-->
<!--  </head>-->

  <body>
    <header class="main">
      <%= image_tag 'logo.png', alt: 'The Pragmatic Book-shelf' %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="content">
      <nav class="side_nav">
        <div id="cart" class="carts">
          <% unless checkout_page %>
            <%= render_if @cart && @cart.line_items.any?, @cart %>
          <% end %>
        </div>
        <ul>
          <li><%= link_to 'Home', store_index_path %></li>
          <li><%= link_to 'Questions', '#' %></li>
          <li><%= link_to 'News', '#' %></li>
          <li><%= link_to 'Contact', '#' %></li>
        </ul>

        <% if session[:user_id] %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders', '#' %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </nav>
        <% end %>
      </nav>
      <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>
  </body>
</html>